name: test

env:
  DOWNLOAD_CACHE_VERSION: 2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: clang-format
        run: |
          clang-format --dry-run --Werror src/*.c include/*.h

  ubuntu:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install cmake ccache valgrind libcriterion-dev libsoundio-dev \
            libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev \
            libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev libglfw3-dev
          mkdir -p ~/.ccache
      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/CMakeLists.txt') }}-${{ env.DOWNLOAD_CACHE_VERSION }}
      - name: Compile with CMake
        run: |
          mkdir -p build
          cd build
          cmake .. -D CMAKE_BUILD_TYPE=Debug -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache
          cmake --build .
      - name: Run Unit tests
        run: |
          # ./build/unit_tests --verbose=1
          valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ./build/unit_tests --verbose=1

