name: test

env:
  DOWNLOAD_CACHE_VERSION: 8

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: clang-format
        run: |
          clang-format --dry-run --Werror src/*.c include/*.h

  ubuntu:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install cmake ccache libcriterion-dev libsoundio-dev \
            libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev \
            libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev libglfw3-dev
          mkdir -p ~/.ccache
      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/CMakeLists.txt') }}-${{ env.DOWNLOAD_CACHE_VERSION }}
      - name: Compile with CMake
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug CC="ccache gcc"
          cmake --build .
      - name: Run Unit tests
        run: |
          cd build
          ctest --output-on-failure
